FROM docker.io/bitnami/spark:2.4.6
RUN curl https://repo.maven.apache.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/2.4.6/spark-sql-kafka-0-10_2.11-2.4.6.jar \
    --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.11-2.4.6.jar
