version: '3.8'

services:
  spark:
    build: ./spark_build
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./spark_data/conf:/opt/bitnami/spark/conf
  spark-worker-1:
    build: ./spark_build
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./spark_data/conf:/opt/bitnami/spark/conf
  spark-worker-2:
    build: ./spark_build
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./spark_data/conf:/opt/bitnami/spark/conf
  fluentd_forward:
    image: docker.io/bitnami/fluentd:1
    ports:
      - '24224:24224'
      - '5140:5140'
  fluentd_http:
    image: docker.io/bitnami/fluentd:1
    ports:
      - '9999:9999'
    volumes:
      - ./fluentd_data/conf:/opt/bitnami/fluentd/conf
      - ./fluentd_data/pos:/opt/bitnami/fluentd/logs/fluentd
      - ./sensor_data:/opt/bitnami/fluentd/logs/sensor_data
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
